FROM ubuntu:19.04

MAINTAINER Theodore Kisner <tskisner@lbl.gov>

# Use bash

SHELL ["/bin/bash", "-c"]

# Install system dependencies.

RUN apt-get update \
    && apt-get install -y \
    curl \
    procps \
    build-essential \
    gfortran \
    git \
    autoconf \
    automake \
    libtool \
    m4 \
    locales \
    libgl1-mesa-glx \
    xvfb \
    python3 \
    libpython3-dev \
    python3-pip \
    && rm -fr /var/lib/apt/lists/*

# Set up locales, to workaround a pip bug

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# We install everything directly into /usr so that we do
# not need to modify the default library and executable
# search paths.  Shifter will manipulate LD_LIBRARY_PATH,
# so it is important not to use that variable.

# Create a home directory for builds

RUN mkdir /home/cmbenv
RUN mkdir /home/cmbenv/.astropy
WORKDIR /home/cmbenv
ENV HOME /home/cmbenv

# Copy files into place

RUN mkdir -p /home/cmbenv/Dockerfile_@CONFIG@_pkgs
COPY Dockerfile_@CONFIG@_pkgs /home/cmbenv/Dockerfile_@CONFIG@_pkgs/

RUN ls -al

# Make site-packages directory

RUN mkdir -p /usr/lib/python@PYVERSION@/site-packages

# Remove conflicting python stuff

ENV PYTHONPATH ""
ENV PYTHONSTARTUP ""
ENV PYTHONNOUSERSITE "1"
ENV PYTHONUSERBASE "/tmp"

# Install packages

@PACKAGES@

# Precompile all python modules

RUN python3 -m compileall -q "/usr/lib/python@PYVERSION@/site-packages"

# Imports to create config files

RUN python3 -c "import astropy"
RUN python3 -c "import matplotlib.font_manager as fm; f = fm.FontManager"

# Set the entrypoint and default command

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
