FROM ubuntu:18.04

MAINTAINER Theodore Kisner <tskisner@lbl.gov>

# Use bash

SHELL ["/bin/bash", "-c"]

# Install system dependencies.

RUN apt-get update \
    && apt-get install -y curl procps build-essential gfortran git subversion \
    autoconf automake libtool m4 cmake locales libfftw3-dev libopenblas-dev \
    libgl1-mesa-glx xvfb \
    && rm -fr /var/lib/apt/lists/*

# Set up locales, to workaround a pip bug

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# We install everything directly into /usr so that we do
# not need to modify the default library and executable
# search paths.  Shifter will manipulate LD_LIBRARY_PATH,
# so it is important not to use that variable.

# Working directory for builds

WORKDIR /usr/src

# Remove conflicting python stuff

ENV PYTHONPATH ""
ENV PYTHONSTARTUP ""
ENV PYTHONNOUSERSITE "1"
ENV PYTHONUSERBASE "/tmp"

# Install packages

@PACKAGES@

# Precompile all python modules

RUN python -m compileall -q "/usr/lib/python@PYVERSION@/site-packages"

# Create a fake home directory so that packages can create
# config files if needed

RUN mkdir /home/cmbenv
RUN mkdir /home/cmbenv/.astropy

WORKDIR /home/cmbenv
ENV HOME /home/cmbenv

RUN python -c "import astropy"
RUN python -c "import matplotlib.font_manager as fm; f = fm.FontManager"

# Set the entrypoint and default command

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
