# Deploy an image with all tools and latest python.  Also deploy images
# with just the toast dependencies for various versions of python.  These can
# be used in toast CI testing.

name:  CMBenv Docker Deploy

on:
  push:
    tags:
      - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  full:
    name: Docker Deploy Python ${{ matrix.python }} ${{ matrix.mpi }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.9
            mpi: mpich
          - python: 3.9
            mpi: openmpi
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: ./cmbenv -c docker-py${{ matrix.python }}-debian-${{ matrix.mpi }}

      - name: Set tag name
        run: tag=$(echo "${GITHUB_REF}" | sed -e 's/.*\/\(v.*\)/\1/') && echo "TAGNAME=${tag}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv-${{ matrix.mpi }}:${TAGNAME} -f Dockerfile_docker-py${{ matrix.python }}-debian-${{ matrix.mpi }} .

      - name: Test Docker Image
        run: docker run -e "OMPI_ALLOW_RUN_AS_ROOT=1" -e "OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1" hpc4cmb/cmbenv-${{ matrix.mpi }}:${TAGNAME} python -c 'import toast.tests; toast.tests.run()'

      - name: Tag Latest
        run: docker tag hpc4cmb/cmbenv-${{ matrix.mpi }}:${TAGNAME} hpc4cmb/cmbenv-${{ matrix.mpi }}:latest

      - name: Push Docker Image
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && docker push hpc4cmb/cmbenv-${{ matrix.mpi }}:${TAGNAME} && docker push hpc4cmb/cmbenv-${{ matrix.mpi }}:latest

  toastdeps:
    name: TOAST Dependencies Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 37
          - python: 38
          - python: 39
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: ./cmbenv -c docker-toastdeps-py${{ matrix.python }}

      - name: Set tag name
        run: tag=$(echo "${GITHUB_REF}" | sed -e 's/.*\/\(v.*\)/\1/') && echo "TAGNAME=${tag}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t hpc4cmb/toast-deps-py${{ matrix.python }}:${TAGNAME} -f Dockerfile_docker-toastdeps-py${{ matrix.python }} .

      - name: Tag Latest
        run: docker tag hpc4cmb/toast-deps-py${{ matrix.python }}:${TAGNAME} hpc4cmb/toast-deps-py${{ matrix.python }}:latest

      - name: Push Docker Image
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && docker push hpc4cmb/toast-deps-py${{ matrix.python }}:${TAGNAME} && docker push hpc4cmb/toast-deps-py${{ matrix.python }}:latest
