# Test action that attempts to generate new docker containers on push to master

name:  CMBenv Docker Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  py37:
    name: Docker Py3.7 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.7-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py37 -f Dockerfile_docker-py3.7-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py37 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py37 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  py38:
    name: Docker Py3.8 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.8-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py38 -f Dockerfile_docker-py3.8-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py38 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py38 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  py39:
    name: Docker Py3.9 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.9-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py39 -f Dockerfile_docker-py3.9-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py39 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py39 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
