# Test action that attempts to generate new docker containers on push to master

name:  CMBenv Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  py36:
    name: Docker Py3.6 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.6-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py36 -f Dockerfile_docker-py3.6-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py36 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py36 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  py37:
    name: Docker Py3.7 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.7-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py37 -f Dockerfile_docker-py3.7-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py37 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py37 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  py38:
    name: Docker Py3.8 Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: ./cmbenv -c docker-py3.8-debian -p /usr/local
      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py38 -f Dockerfile_docker-py3.8-debian .
      - name: Test Docker Image
        run: docker run hpc4cmb/cmbenv:temp_py38 python -c 'import toast.tests; toast.tests.run()' && docker run hpc4cmb/cmbenv:temp_py38 mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  macos-venv-clang:
    name: MacOS Virtualenv Clang
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Install Script
        run: ./cmbenv -c macos-venv-clang -p ~/cmbenv
      - name: Install Packages
        run:  mkdir build; cd build; ../install_macos-venv-clang.sh; cd ..; . ~/cmbenv/cmbenv_init.sh; mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
  macos-venv-gcc:
    name: MacOS Virtualenv GCC
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Install Script
        run: ./cmbenv -c macos-venv-gcc -p ~/cmbenv
      - name: Install Packages
        run:  mkdir build; cd build; ../install_macos-venv-gcc.sh; cd ..; . ~/cmbenv/cmbenv_init.sh; mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
