# Test action that attempts to generate new docker containers on push to master

name:  CMBenv Docker Test

on:
  pull_request:
    branches: [ master ]
  # push:
  #   branches: [ master ]

jobs:
  test:
    name: Docker Test Python ${{ matrix.python }} ${{ matrix.mpi }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.7
            mpi: mpich
          - python: 3.8
            mpi: mpich
          - python: 3.9
            mpi: mpich
          - python: 3.9
            mpi: openmpi
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: ./cmbenv -c docker-py${{ matrix.python }}-debian-${{ matrix.mpi }}

      - name: Build Docker Image
        run: docker build -t hpc4cmb/cmbenv:temp_py${{ matrix.python }}_${{ matrix.mpi }} -f Dockerfile_docker-py${{ matrix.python }}-debian-${{ matrix.mpi }} .

      - name: Test Docker Image
        run: docker run -e "OMPI_ALLOW_RUN_AS_ROOT=1" -e "OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1" hpc4cmb/cmbenv:temp_py${{ matrix.python }}_${{ matrix.mpi }} python -c 'import toast.tests; toast.tests.run()' && docker run -e "OMPI_ALLOW_RUN_AS_ROOT=1" -e "OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1" hpc4cmb/cmbenv:temp_py${{ matrix.python }}_${{ matrix.mpi }} mpirun -np 2 python -c 'import toast.tests; toast.tests.run()'
